USE [master]
GO
/****** Object:  Database [PRJ]    Script Date: 9/16/2023 4:17:20 PM ******/
CREATE DATABASE [PRJ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRJ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PRJ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRJ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PRJ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PRJ] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRJ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRJ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRJ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRJ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRJ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRJ] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRJ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRJ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRJ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRJ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRJ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRJ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRJ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRJ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRJ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRJ] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PRJ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRJ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRJ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRJ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRJ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRJ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRJ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRJ] SET RECOVERY FULL 
GO
ALTER DATABASE [PRJ] SET  MULTI_USER 
GO
ALTER DATABASE [PRJ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRJ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRJ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRJ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRJ] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRJ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PRJ', N'ON'
GO
ALTER DATABASE [PRJ] SET QUERY_STORE = ON
GO
ALTER DATABASE [PRJ] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PRJ]
GO
/****** Object:  Table [dbo].[account]    Script Date: 9/16/2023 4:17:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[account](
	[username] [nvarchar](50) NOT NULL,
	[password] [nvarchar](50) NOT NULL,
	[status] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sets]    Script Date: 9/16/2023 4:17:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sets](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[owner] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[word]    Script Date: 9/16/2023 4:17:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[word](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[word] [nvarchar](50) NOT NULL,
	[meaning] [nvarchar](50) NOT NULL,
	[setID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[sets]  WITH CHECK ADD FOREIGN KEY([owner])
REFERENCES [dbo].[account] ([username])
GO
ALTER TABLE [dbo].[word]  WITH CHECK ADD FOREIGN KEY([setID])
REFERENCES [dbo].[sets] ([id])
GO
USE [master]
GO
ALTER DATABASE [PRJ] SET  READ_WRITE 
GO
